import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    MatButtonModule,
    MatNativeDateModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatToolbarModule,
    MatTableModule,
    MatPaginatorModule,
    MatFormFieldModule,
    MatDialogModule,
    MatInputModule,
    MatCheckboxModule,
    MatSelectModule,
    MatOptionModule,
    MatProgressBarModule,
    MatSortModule,
    MatDatepickerModule,
    MatCardModule,
} from '@angular/material';

@NgModule({
    imports: [CommonModule,
        MatButtonModule,
        MatToolbarModule,
        MatNativeDateModule,
        MatIconModule,
        MatSidenavModule,
        MatListModule,
        MatTableModule,
        MatPaginatorModule,
        MatFormFieldModule,
        MatDialogModule,
        MatInputModule,
        MatCheckboxModule,
        MatSelectModule,
        MatProgressBarModule,
        MatSortModule,
        MatDatepickerModule,
        MatCardModule
    ],

    exports: [CommonModule,
        MatButtonModule,
        MatToolbarModule,
        MatNativeDateModule,
        MatIconModule,
        MatSidenavModule,
        MatListModule,
        MatTableModule,
        MatPaginatorModule,
        MatFormFieldModule,
        MatDialogModule,
        MatInputModule,
        MatCheckboxModule,
        MatOptionModule,
        MatSelectModule,
        MatProgressBarModule,
        MatSortModule,
        MatDatepickerModule,
        MatCardModule]
})
export class CustomMaterialModule { }
